### ISSUE TITLE
run.py syntax error

### ISSUE THREAD

**Issue by aahmed23** [imodpasteur/ANNA-PALM#11]
hello,
i am getting this error message when i try to run the run.py command line
 li@biophotonics:~/Documents/ANNA$ python run.py --workdir=./tmp_test --ngf=1 --ndf=1
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from smlm_datasets import create_data_sources
  File "/home/li/Documents/ANNA/smlm_datasets.py", line 254
    print('X', end = '')
                   ^
SyntaxError: invalid syntax

**Comment by oeway** [comment]
hi, sorry, I can't reproduce your error. Could you give more information about your OS, python version, etc.

In order to run the code, please make sure your are using the latest version of the code and Python 3.6 or 3.5 (not Python 2)?
