### ISSUE TITLE
ImportError: cannot import name 'TUBULIN'

### ISSUE THREAD

**Issue by duancaohui** [imodpasteur/ANNA-PALM#12]
`from AnetLib.data.datasets import TUBULIN, NUCLEAR_PORE`

`ImportError: cannot import name 'TUBULIN'`

In your datasets, there is no class named 'TUBULIN'`, is it necessary change it to 'NpzDataset'

**Comment by oeway** [comment]
Hi,
Please make sure you are using the latest version of the code.
You can find it here: https://github.com/imodpasteur/ANNA-PALM/blob/55d137a0d9486ef86a132b54beb3ad3aa5338a95/datasets.py
