### ISSUE TITLE
Fail to run run.py

### ISSUE THREAD

**Issue by yemaopt** [imodpasteur/ANNA-PALM#15]
Hello,
I used conda to create a vitual enviroment with python=3.6
conda create -n annaenv python=3.6

and install the package by
cd ANNA-PALM
pip install -r requirements-gpu.txt

The installation process is smooth, but when I run
python run.py --workdir=./tmp_test --ngf=1 --ndf=1

I came across the following errors. Could you give me some suggestions?
Many thanks for your help!

![Picture1](https://user-images.githubusercontent.com/50851106/63643395-63521680-c69d-11e9-9e55-3ecd3678789a.png)
![Picture2](https://user-images.githubusercontent.com/50851106/63643396-65b47080-c69d-11e9-9fc2-5eab0408abbd.png)
![Picture3](https://user-images.githubusercontent.com/50851106/63643397-677e3400-c69d-11e9-84e7-90c6b898b0d9.png)

**Comment by oeway** [comment]
Hi, that error occurred because scipy removed the bytescale function in new versions. To fix it, try:

pip install scipy==1.0.0

**Comment by yemaopt** [comment]
Hello,
Thank you so much! That's the problem.
Sincerely yours,
Ye
