### ISSUE TITLE
Color images are not available

### ISSUE THREAD

**Issue by kp-1** [imodpasteur/ANNA-PALM#18]
Hi, I'm curious how did you get the color picture in the paper, I tried with my own picture and got the grayscale picture

**Comment by oeway** [comment]
You can color code an grayscale image by using Lookup Table, for example,
open your image in imagej and apply the an lookup table:
https://imagej.nih.gov/ij/docs/menus/image.html#tables

**Comment by kp-1** [comment]
I'm just curious how did you get the picture that you used in the paper? I use python source code to test, but the parameters in the source code is very strange, input channel number is 2 only, if I change it into 3 encounters an error, so, I can only put the images into a single channel which is the grayscale can use your code to predict, so I get is gray, I look at the source, output channel is 1, I change it into 3 will also encounters an error, then how did you get your color images?Did you get it the way you told me?

**Comment by oeway** [comment]
Yes, you will get it if you apply a `Red Hot` Lookup table to the single channel grayscale image in ImageJ.
