### ISSUE TITLE
Issue with Dropbox Links for Pretrained Models and Simulated Data in ANNA-PALM

### ISSUE THREAD

**Issue by sylvanding** [imodpasteur/ANNA-PALM#47]
Hello,

I am a student at the Beijing Institute of Technology's [Advanced Research Institute of Multidisciplinary Sciences](https://arims.bit.edu.cn/xztd/qkjs/4c78910cdd044179a185392b4e3bc101.htm). I am currently working on a project focused on super-resolution reconstruction of SMLM.

**I am reaching out because I encountered an issue when attempting to access [the pretrained models](https://www.dropbox.com/sh/dc5l64n7apsgjdo/AABWH9PpfPHAzpbG8zwalIHZa?dl=0) and simulated data [tubulin-sim-800x800.npz](https://www.dropbox.com/s/7v5vmgc3qkd2901/tubulin-sim-800x800.npz?dl=1) for ANNA-PALM. It seems that the Dropbox links provided in the repository are no longer functioning.** These resources are crucial for my research, and I was wondering if you could please regenerate these links.

Thank you for your attention to this matter. I look forward to your prompt response.

Best regards,
@sylvanding
📮 jxd@bit.edu.cn
Postgraduate Student, Beijing Institute of Technology

**Comment by sylvanding** [comment]
@oeway

**Comment by oeway** [comment]
Hi @sylvanding sorry about that, we recently uploaded it to here: https://huggingface.co/datasets/baiddd/ANNA-PALM-dataset/tree/main

**Comment by sylvanding** [comment]
I am fortunate to have someone as generous as you! Thanks!
